Pizzeteria/urls.py
from django.contrib import admin
from django.urls import re_path
from django.urls import include

app_name="Pizza"

urlpatterns = [
    re_path(r'^admin/',admin.site.urls),
    re_path(r'',include('pizzeteria.urls',namespace='pizzeteria')),

]

pizzeteria/urls.py
"""Define URLs Pattern for Pizzeteria."""

from django.urls import re_path
from . import views

app_name="Pizza"

urlpatterns=[
    #Home Page
    re_path('^$',views.index,name='index'),
    re_path(r'^pizza/$', views.pizza, name='pizza'),
    re_path(r'^pizza/(?P<pizza_id>\d+)/$', views.toppings, name='pizza'),
]

pizzeteria/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name=models.TextField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Toppings(models.Model):
    pizza=models.ForeignKey(Pizza,on_delete=models.PROTECT)
    name=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

pizzeteria/views.py
from django.shortcuts import render
from .models import Pizza, Toppings

def index(request):
    """the home page for the Pizzeteria"""
    return render(request,'pizzeteria/index.html')

def pizza(request):
    pizzas=Pizza.objects.order_by('date_added')
    context={'pizzas':pizzas}
    return render(request,'pizzeteria/pizza_name.html',context)

def toppings(request, pizza_id):
    """Show toppings for a specific pizza."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.all()  # Assuming a ForeignKey from Toppings to Pizza
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzeteria/toppings.html', context)

pizzeteria/templates/pizzeteria/base.html
<p>
    <a href="{% url 'pizzeteria:index'%}">Pizzeteria</a> -
    <a href="{% url 'Pizza:pizza' %}">Pizzas</a>
</p>

{% block content %} {% endblock content %}

pizzeteria/templates/pizzeteria/index.html
{% extends "pizzeteria/base.html" %}

{% block content %}
<p>Pizzeteria Helps you find details about your choice of pizza.</p>
{% endblock content %}

pizzeteria/templates/pizzeteria/pizza_name.html
{% extends "pizzeteria/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'pizzeteria:pizza' pizza.id %}">{{ pizza }}</a>
        </li>
    {% empty %}
     <li>No pizza has been added.</li>
    {% endfor %}

</ul>

{% endblock content %}

pizzeteria/templates/pizzeteria/toppings.html
{% extends 'pizzeteria/base.html' %}
{% block content %}
<p>Toppings of : {{ pizza }}</p>
<ul>
{% for topping in toppings %}
<li>
<p>{{ topping.name|linebreaks }}</p>
</li>
{% empty %}
<li>
There are no entries for this topic yet.
</li>
{% endfor %}
</ul>
{% endblock content %}